In [23]:
import pandas as pd
df = pd.read_csv('iphone.csv')
df

,Product Name,Product URL,Brand,Sale Price,Mrp,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,11202,794,MOBEXRGVMZWUHCBA,NaN,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB
...,...,...,...,...,...,...,...,...,...,...
57,"APPLE iPhone SE (Black, 64 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,29999,39900,95909,8161,MOBFWQ6BR3MK7AUG,4.5,4 GB
58,"APPLE iPhone 11 (Purple, 64 GB)",https://www.flipkart.com/apple-iphone-11-purpl...,Apple,46999,54900,43470,3331,MOBFWQ6BTFFJKGKE,4.6,4 GB
59,"APPLE iPhone 11 (White, 64 GB)",https://www.flipkart.com/apple-iphone-11-white...,Apple,46999,54900,43470,3331,MOBFWQ6BVWVEH3XE,4.6,4 GB
60,"APPLE iPhone 11 (Black, 64 GB)",https://www.flipkart.com/apple-iphone-11-black...,Apple,46999,54900,43470,3331,MOBFWQ6BXGJCEYNY,4.6,4 GB
61,"APPLE iPhone 11 (Red, 64 GB)",https://www.flipkart.com/apple-iphone-11-red-6...,Apple,46999,54900,43470,3331,MOBFWQ6BYYV3FCU7,4.6,4 GB

In [24]:
df.columns

Index(['Product Name', 'Product URL', 'Brand', 'Sale Price', 'Mrp',
       'Number Of Ratings', 'Number Of Reviews', 'Upc', 'Star Rating', 'Ram'],
      dtype='object')

In [107]:
#The column names have spaces . rename the column names to have underscore '_' instead of space (try to do in one go instead of specifying each column nam in rename method)

df.columns= df.columns.str.replace(' ', '_')
df.columns

Index(['Product_Name', 'Product_URL', 'Brand', 'Sale_Price', 'Mrp',
       'Number_Of_Ratings', 'Number_Of_Reviews', 'Upc', 'Star_Rating', 'Ram',
       'Discount_Percentage', 'Storage', 'Color'],
      dtype='object')

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Product_Name       62 non-null     object
 1   Product_URL        62 non-null     object
 2   Brand              62 non-null     object
 3   Sale_Price         62 non-null     int64
 4   Mrp                62 non-null     int64
 5   Number_Of_Ratings  62 non-null     int64
 6   Number_Of_Reviews  62 non-null     int64
 7   Upc                62 non-null     object
 8   Star_Rating        59 non-null     float64
 9   Ram                62 non-null     object
dtypes: float64(1), int64(4), object(5)
memory usage: 5.0+ KB

In [27]:
df.isna().sum()

Product_Name         0
Product_URL          0
Brand                0
Sale_Price           0
Mrp                  0
Number_Of_Ratings    0
Number_Of_Reviews    0
Upc                  0
Star_Rating          3
Ram                  0
dtype: int64

In [28]:
#star rating for some of the models is missing in the dataset. fill those missing values with the average rating all the models.

missing_ratings = df[df['Star_Rating'].isna()]
print(missing_ratings[['Product_Name', 'Star_Rating']])

                                  Product_Name  Star_Rating
3              APPLE iPhone 8 (Silver, 256 GB)          NaN
10              Apple iPhone XR (Black, 64 GB)          NaN
32  APPLE iPhone 12 Pro Max (Graphite, 128 GB)          NaN

In [29]:
df['Star_Rating'].isna()

0     False
1     False
2     False
3      True
4     False
      ...
57    False
58    False
59    False
60    False
61    False
Name: Star_Rating, Length: 62, dtype: bool

In [30]:
df[df['Star_Rating'].isna()]

,Product_Name,Product_URL,Brand,Sale_Price,Mrp,Number_Of_Ratings,Number_Of_Reviews,Upc,Star_Rating,Ram
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,11202,794,MOBEXRGVMZWUHCBA,NaN,2 GB
10,"Apple iPhone XR (Black, 64 GB)",https://www.flipkart.com/apple-iphone-xr-black...,Apple,39999,47900,79512,6796,MOBF9Z7ZPHGV4GNH,NaN,4 GB
32,"APPLE iPhone 12 Pro Max (Graphite, 128 GB)",https://www.flipkart.com/apple-iphone-12-pro-m...,Apple,120900,129900,580,45,MOBFWBYZFDGQSDWS,NaN,6 GB

In [31]:
df['Star_Rating'] = df['Star_Rating'].fillna(df['Star_Rating'].mean())

In [32]:
df

,Product_Name,Product_URL,Brand,Sale_Price,Mrp,Number_Of_Ratings,Number_Of_Reviews,Upc,Star_Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,3431,356,MOBEXRGV7EHHTGUH,4.600000,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVAC6TJT4F,4.600000,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVGETABXWZ,4.600000,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,11202,794,MOBEXRGVMZWUHCBA,4.576271,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,11202,794,MOBEXRGVPK7PFEJZ,4.500000,2 GB
...,...,...,...,...,...,...,...,...,...,...
57,"APPLE iPhone SE (Black, 64 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,29999,39900,95909,8161,MOBFWQ6BR3MK7AUG,4.500000,4 GB
58,"APPLE iPhone 11 (Purple, 64 GB)",https://www.flipkart.com/apple-iphone-11-purpl...,Apple,46999,54900,43470,3331,MOBFWQ6BTFFJKGKE,4.600000,4 GB
59,"APPLE iPhone 11 (White, 64 GB)",https://www.flipkart.com/apple-iphone-11-white...,Apple,46999,54900,43470,3331,MOBFWQ6BVWVEH3XE,4.600000,4 GB
60,"APPLE iPhone 11 (Black, 64 GB)",https://www.flipkart.com/apple-iphone-11-black...,Apple,46999,54900,43470,3331,MOBFWQ6BXGJCEYNY,4.600000,4 GB
61,"APPLE iPhone 11 (Red, 64 GB)",https://www.flipkart.com/apple-iphone-11-red-6...,Apple,46999,54900,43470,3331,MOBFWQ6BYYV3FCU7,4.600000,4 GB

In [34]:
#df['Star_Rating'] = df.groupby('Ram')['Star_Rating'].transform(lambda x: x.fillna(x.mean()))
df['Star_Rating'].dtype

dtype('float64')

In [39]:
# Now instead of filling missing values with avg rating of full dataset , fill with avg rating based on RAM. example :  if rating for a 2 gb phone is missing then take average of all other 2 gb phones rating and fill that value.
df['Star_Rating'] = df.groupby('Ram')['Star_Rating'].transform(lambda x: x.fillna(x.mean()))
df

,Product_Name,Product_URL,Brand,Sale_Price,Mrp,Number_Of_Ratings,Number_Of_Reviews,Upc,Star_Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,3431,356,MOBEXRGV7EHHTGUH,4.600000,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVAC6TJT4F,4.600000,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVGETABXWZ,4.600000,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,11202,794,MOBEXRGVMZWUHCBA,4.576271,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,11202,794,MOBEXRGVPK7PFEJZ,4.500000,2 GB
...,...,...,...,...,...,...,...,...,...,...
57,"APPLE iPhone SE (Black, 64 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,29999,39900,95909,8161,MOBFWQ6BR3MK7AUG,4.500000,4 GB
58,"APPLE iPhone 11 (Purple, 64 GB)",https://www.flipkart.com/apple-iphone-11-purpl...,Apple,46999,54900,43470,3331,MOBFWQ6BTFFJKGKE,4.600000,4 GB
59,"APPLE iPhone 11 (White, 64 GB)",https://www.flipkart.com/apple-iphone-11-white...,Apple,46999,54900,43470,3331,MOBFWQ6BVWVEH3XE,4.600000,4 GB
60,"APPLE iPhone 11 (Black, 64 GB)",https://www.flipkart.com/apple-iphone-11-black...,Apple,46999,54900,43470,3331,MOBFWQ6BXGJCEYNY,4.600000,4 GB
61,"APPLE iPhone 11 (Red, 64 GB)",https://www.flipkart.com/apple-iphone-11-red-6...,Apple,46999,54900,43470,3331,MOBFWQ6BYYV3FCU7,4.600000,4 GB

In [41]:
# create a new column in the dataframe "Discount_Percentage" based on MRP and sale value

df['Discount_Percentage'] = ((df['Mrp'] - df['Sale_Price']) / df['Mrp']) * 100
df

,Product_Name,Product_URL,Brand,Sale_Price,Mrp,Number_Of_Ratings,Number_Of_Reviews,Upc,Star_Rating,Ram,Discount_Percentage
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,3431,356,MOBEXRGV7EHHTGUH,4.600000,2 GB,0.000000
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVAC6TJT4F,4.600000,2 GB,0.000000
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVGETABXWZ,4.600000,2 GB,0.000000
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,11202,794,MOBEXRGVMZWUHCBA,4.576271,2 GB,0.000000
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,11202,794,MOBEXRGVPK7PFEJZ,4.500000,2 GB,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
57,"APPLE iPhone SE (Black, 64 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,29999,39900,95909,8161,MOBFWQ6BR3MK7AUG,4.500000,4 GB,24.814536
58,"APPLE iPhone 11 (Purple, 64 GB)",https://www.flipkart.com/apple-iphone-11-purpl...,Apple,46999,54900,43470,3331,MOBFWQ6BTFFJKGKE,4.600000,4 GB,14.391621
59,"APPLE iPhone 11 (White, 64 GB)",https://www.flipkart.com/apple-iphone-11-white...,Apple,46999,54900,43470,3331,MOBFWQ6BVWVEH3XE,4.600000,4 GB,14.391621
60,"APPLE iPhone 11 (Black, 64 GB)",https://www.flipkart.com/apple-iphone-11-black...,Apple,46999,54900,43470,3331,MOBFWQ6BXGJCEYNY,4.600000,4 GB,14.391621
61,"APPLE iPhone 11 (Red, 64 GB)",https://www.flipkart.com/apple-iphone-11-red-6...,Apple,46999,54900,43470,3331,MOBFWQ6BYYV3FCU7,4.600000,4 GB,14.391621

In [47]:
# which model has highest percent discount ?

df = df.sort_values(by='Discount_Percentage', ascending=False)
df

,Product_Name,Product_URL,Brand,Sale_Price,Mrp,Number_Of_Ratings,Number_Of_Reviews,Upc,Star_Rating,Ram,Discount_Percentage
18,"APPLE iPhone 11 Pro (Midnight Green, 64 GB)",https://www.flipkart.com/apple-iphone-11-pro-m...,Apple,74999,106600,7088,523,MOBFKCTSN3TG3RFJ,4.6,4 GB,29.644465
57,"APPLE iPhone SE (Black, 64 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,29999,39900,95909,8161,MOBFWQ6BR3MK7AUG,4.5,4 GB,24.814536
52,"APPLE iPhone SE (White, 64 GB)",https://www.flipkart.com/apple-iphone-se-white...,Apple,29999,39900,95807,8154,MOBFWQ6BGWDVGF3E,4.5,2 GB,24.814536
53,"APPLE iPhone SE (Black, 128 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,34999,44900,95909,8161,MOBFWQ6BHUEVZPXD,4.5,2 GB,22.051225
54,"APPLE iPhone SE (White, 128 GB)",https://www.flipkart.com/apple-iphone-se-white...,Apple,34999,44900,95807,8154,MOBFWQ6BJEHMUUZY,4.5,2 GB,22.051225
...,...,...,...,...,...,...,...,...,...,...,...
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB,0.000000
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB,0.000000
7,"APPLE iPhone 8 (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-space-...,Apple,77000,77000,11202,794,MOBEXRGVZFZGZEWV,4.5,2 GB,0.000000
6,"APPLE iPhone 8 Plus (Space Grey, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,49900,49900,3431,356,MOBEXRGVQKBREZP8,4.6,2 GB,0.000000
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB,0.000000

In [46]:
max_discount_model = df.loc[df['Discount_Percentage'].idxmax(), 'Product_Name']
max_discount_value = df['Discount_Percentage'].max()
max_discount_model

'APPLE iPhone 11 Pro (Midnight Green, 64 GB)'

In [49]:
# find total no of models each space configuration (128 GB , 64 GB etc)

df['Storage'] = df['Product_Name'].str.extract(r'(\d+\s*GB)')
storage_counts = df['Storage'].value_counts()
print(storage_counts)

Storage
128 GB    24
64 GB     20
256 GB    14
512 GB     4
Name: count, dtype: int64

In [52]:
# find total number of models for each color 
import re

# Function to extract color from product name
def extract_color(product_name):
    match = re.search(r"\(([^,]+),", product_name)  # Captures everything before the comma
    return match.group(1).strip() if match else None  # Remove extra spaces if any

# Apply function to create a new column 'Color'
df['Color'] = df['Product_Name'].apply(extract_color)

# Display the updated DataFrame
print(df[['Product_Name', 'Color']].head())

                                   Product_Name           Color
18  APPLE iPhone 11 Pro (Midnight Green, 64 GB)  Midnight Green
57               APPLE iPhone SE (Black, 64 GB)           Black
52               APPLE iPhone SE (White, 64 GB)           White
53              APPLE iPhone SE (Black, 128 GB)           Black
54              APPLE iPhone SE (White, 128 GB)           White

In [53]:
df

,Product_Name,Product_URL,Brand,Sale_Price,Mrp,Number_Of_Ratings,Number_Of_Reviews,Upc,Star_Rating,Ram,Discount_Percentage,Storage,Color
18,"APPLE iPhone 11 Pro (Midnight Green, 64 GB)",https://www.flipkart.com/apple-iphone-11-pro-m...,Apple,74999,106600,7088,523,MOBFKCTSN3TG3RFJ,4.6,4 GB,29.644465,64 GB,Midnight Green
57,"APPLE iPhone SE (Black, 64 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,29999,39900,95909,8161,MOBFWQ6BR3MK7AUG,4.5,4 GB,24.814536,64 GB,Black
52,"APPLE iPhone SE (White, 64 GB)",https://www.flipkart.com/apple-iphone-se-white...,Apple,29999,39900,95807,8154,MOBFWQ6BGWDVGF3E,4.5,2 GB,24.814536,64 GB,White
53,"APPLE iPhone SE (Black, 128 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,34999,44900,95909,8161,MOBFWQ6BHUEVZPXD,4.5,2 GB,22.051225,128 GB,Black
54,"APPLE iPhone SE (White, 128 GB)",https://www.flipkart.com/apple-iphone-se-white...,Apple,34999,44900,95807,8154,MOBFWQ6BJEHMUUZY,4.5,2 GB,22.051225,128 GB,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB,0.000000,256 GB,Silver
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB,0.000000,256 GB,Space Grey
7,"APPLE iPhone 8 (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-space-...,Apple,77000,77000,11202,794,MOBEXRGVZFZGZEWV,4.5,2 GB,0.000000,256 GB,Space Grey
6,"APPLE iPhone 8 Plus (Space Grey, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,49900,49900,3431,356,MOBEXRGVQKBREZP8,4.6,2 GB,0.000000,64 GB,Space Grey
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB,0.000000,64 GB,Gold

In [54]:
#find total number of models for each color 
color_counts = df['Color'].value_counts()
print(color_counts)

Color
Black             10
White             10
Silver             7
Space Grey         6
Gold               6
Red                5
Pacific Blue       4
Graphite           4
Midnight Green     4
Blue               2
RED                1
Coral              1
Green              1
Purple             1
Name: count, dtype: int64

In [61]:
# list top 5 models having highest no of reviews 
df = df.sort_values(by='Number_Of_Reviews', ascending=False)
#df.head(5)
df[['Product_Name', 'Number_Of_Reviews']].head(5)

                       Product_Name  Number_Of_Reviews
57   APPLE iPhone SE (Black, 64 GB)               8161
53  APPLE iPhone SE (Black, 128 GB)               8161
55    APPLE iPhone SE (Red, 128 GB)               8161
23  Apple iPhone SE (White, 256 GB)               8161
54  APPLE iPhone SE (White, 128 GB)               8154

In [63]:
# price diffrence between highest price and lowest price iphone (based on mrp)
price_difference = df['Mrp'].max() - df['Mrp'].min()
print("Price Difference:", price_difference)

Price Difference: 110000

In [67]:
# find total no of reviews for iphone 11 and iphone 12 category . Output should have only 2 rows (for 11 and 12).

# Filter the DataFrame for iPhone 11 and iPhone 12 categories
iphone_11_reviews = df[df['Product_Name'].str.contains('iPhone 11', case=False)]
iphone_12_reviews = df[df['Product_Name'].str.contains('iPhone 12', case=False)]

# Calculate the total number of reviews for each category
total_reviews_11 = iphone_11_reviews['Number_Of_Reviews'].sum()
total_reviews_12 = iphone_12_reviews['Number_Of_Reviews'].sum()

# Create a new DataFrame with the results
result_df = pd.DataFrame({
    'iPhone Category': ['iPhone 11', 'iPhone 12'],
    'Total Reviews': [total_reviews_11, total_reviews_12]
})

In [68]:
result_df

  iPhone Category  Total Reviews
0       iPhone 11          25965
1       iPhone 12           2208

In [71]:
# which iphone has 3rd highest MRP
df_sorted = df.sort_values(by='Mrp', ascending=False)

third_highest_iphone = df_sorted.iloc[2]  

print(third_highest_iphone[['Product_Name', 'Mrp']])

Product_Name    APPLE iPhone 11 Pro (Space Grey, 512 GB)
Mrp                                               140300
Name: 19, dtype: object

In [73]:
# what is the average mrp of iphones which costs above 100,000
high_price_iphones = df[df['Mrp'] > 100000]

average_mrp = high_price_iphones['Mrp'].mean()

print(f"Average MRP of iPhones above â‚¹100,000: â‚¹{average_mrp:.2f}")

Average MRP of iPhones above â‚¹100,000: â‚¹130559.09

In [106]:
# which iphone with 128 GB space has highest ratings to review ratio
# Filter the DataFrame to include only iPhones with 128 GB of space
#df['Storage'] = df['Storage'].str.extract(r'(\d+)').astype(int)


df['Storage'] = df['Storage'].astype(str).str.extract(r'(\d+)').astype(float)
iphone_128gb = df[df['Storage'] == 128]

iphone_128gb

iphone_128gb['Ratings to Reviews Ratio'] = iphone_128gb['Number_Of_Ratings'] / iphone_128gb['Number_Of_Reviews']
iphone_128gb['Ratings to Reviews Ratio']

highest_ratio_iphone = iphone_128gb.loc[iphone_128gb['Ratings to Reviews Ratio'].idxmax()]
highest_ratio_iphone

C:\Users\MSII\AppData\Local\Temp\ipykernel_17992\1230756763.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iphone_128gb['Ratings to Reviews Ratio'] = iphone_128gb['Number_Of_Ratings'] / iphone_128gb['Number_Of_Reviews']

Product_Name                                  APPLE iPhone 11 (Black, 128 GB)
Product_URL                 https://www.flipkart.com/apple-iphone-11-black...
Brand                                                                   Apple
Sale_Price                                                              54999
Mrp                                                                     59900
Number_Of_Ratings                                                       43470
Number_Of_Reviews                                                        3331
Upc                                                          MOBFWQ6BKRYBP5X8
Star_Rating                                                               4.6
Ram                                                                      4 GB
Discount_Percentage                                                   8.18197
Storage                                                                 128.0
Color                                                                   Black
Ratings to Reviews Ratio                                            13.050135
Name: 56, dtype: object